package com.mobilosophy.sallyhansen.constant;

import java.util.ArrayList;
import java.util.List;

import com.mobilosophy.sallyhansen.model.StoredCMLDataSet;

import android.app.Activity;

public class Constants {

	public static final String CONSUMER_KEY = "bRkBxBLZ1txY1dX3LYzqw";
	public static final String CONSUMER_SECRET = "qPj6pnhHbA16RjaLwefoCnwDDh6BxAoZQufakiyQ";
	public static String FACEBOOK_APP_ID = "559198684133538";
	public static final String[] fb_permissions = { "offline_access",
			"publish_stream", "user_photos", "publish_checkins", "photo_upload" };
	public final static int FACEBOOK_AUTHORIZE_ACTIVITY_RESULT_CODE = 0;
	public final static int FACEBOOK_PICK_EXISTING_PHOTO_RESULT_CODE = 1;
	public static String PINTEREST_CLIENT_ID = "1433459";

	public static int[][] HAND_COLOR_ARRAY = new int[][] { { 246, 219, 200, },
			{ 241, 200, 172 }, { 222, 168, 141 }, { 199, 147, 119 },
			{ 156, 100, 72 } };

	public static Activity ACTIVITY_TO_CLOSE;
	public static StoredCMLDataSet USER_CREATED_CML;

	public static int THUMB_FINGER = 0, INDEX_FINGER = 1, MIDDLE_FINGER = 2,
			RING_FINGER = 3, PINKIE_FINGER = 4;

	public static boolean IS_NAIL_EDITED = false;

	public static int SCREEN_RESOLUTION_MDPI = 320,
			SCREEN_RESOLUTION_HDPI = 480, SCREEN_RESOLUTION_XHDPI = 720;

	public static int RIGHT_OPEN_HAND_THUMB_ANGLE = 170,
			RIGHT_OPEN_HAND_INDEX_ANGLE = 180,
			RIGHT_OPEN_HAND_MIDDLE_ANGLE = 180,
			RIGHT_OPEN_HAND_RING_ANGLE = 180,
			RIGHT_OPEN_HAND_PINKIE_ANGLE = 180,
			LEFT_CLOSE_HAND_THUMB_ANGLE = 245,
			LEFT_CLOSE_HAND_INDEX_ANGLE = 346,
			LEFT_CLOSE_HAND_MIDDLE_ANGLE = 0, LEFT_CLOSE_HAND_RING_ANGLE = 10,
			LEFT_CLOSE_HAND_PINKIE_ANGLE = 38, CURRENT_THUMB_ANGLE = 0,
			CURRENT_INDEX_ANGLE = 0, CURRENT_MIDDLE_ANGLE = 0,
			CURRENT_RING_ANGLE = 0, CURRENT_PINKIE_ANGLE = 0,
			CURRENT_HAND_INDEX_FINGER_LEFT_MARGIN = -1,
			CURRENT_HAND_INDEX_FINGER_TOP_MARGIN = -1,
			CURRENT_HAND_MIDDLE_FINGER_LEFT_MARGIN = -1,
			CURRENT_HAND_MIDDLE_FINGER_TOP_MARGIN = -1,
			CURRENT_HAND_RING_FINGER_LEFT_MARGIN = -1,
			CURRENT_HAND_RING_FINGER_TOP_MARGIN = -1,
			CURRENT_HAND_PINKIE_FINGER_LEFT_MARGIN = -1,
			CURRENT_HAND_PINKIE_FINGER_TOP_MARGIN = -1,
			CURRENT_HAND_THUMB_FINGER_LEFT_MARGIN = -1,
			CURRENT_HAND_THUMB_FINGER_TOP_MARGIN = -1;

	public static int ROUNDED_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_1 = 147,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_1 = 108,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_1 = 225,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_1 = 55,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_1 = 308,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_1 = 88,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_1 = 394,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_1 = 156,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_1 = 36,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_1 = 310,

			ROUNDED_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_1 = 133,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_1 = 216,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_1 = 198,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_1 = 205,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_1 = 256,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_1 = 242,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_1 = 301,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_1 = 280,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_1 = 146,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_1 = 295;

	public static int OVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_1 = 147,
			OVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_1 = 108,
			OVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_1 = 225,
			OVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_1 = 55,
			OVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_1 = 308,
			OVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_1 = 88,
			OVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_1 = 394,
			OVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_1 = 156,
			OVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_1 = 36,
			OVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_1 = 310,

			OVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_1 = 133,
			OVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_1 = 216,
			OVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_1 = 198,
			OVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_1 = 207,
			OVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_1 = 256,
			OVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_1 = 242,
			OVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_1 = 301,
			OVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_1 = 280,
			OVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_1 = 146,
			OVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_1 = 295;

	public static int SQUOVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_1 = 147,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_1 = 108,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_1 = 225,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_1 = 55,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_1 = 308,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_1 = 88,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_1 = 394,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_1 = 156,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_1 = 36,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_1 = 310,

			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_1 = 133,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_1 = 216,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_1 = 198,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_1 = 205,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_1 = 254,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_1 = 242,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_1 = 301,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_1 = 280,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_1 = 146,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_1 = 295;

	public static int SQUARE_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_1 = 147,
			SQUARE_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_1 = 108,
			SQUARE_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_1 = 225,
			SQUARE_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_1 = 55,
			SQUARE_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_1 = 308,
			SQUARE_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_1 = 88,
			SQUARE_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_1 = 394,
			SQUARE_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_1 = 156,
			SQUARE_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_1 = 36,
			SQUARE_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_1 = 310,

			SQUARE_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_1 = 133,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_1 = 216,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_1 = 198,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_1 = 205,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_1 = 256,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_1 = 242,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_1 = 301,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_1 = 280,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_1 = 146,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_1 = 295;

	public static int STILETTO_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_1 = 147,
			STILETTO_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_1 = 108,
			STILETTO_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_1 = 225,
			STILETTO_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_1 = 55,
			STILETTO_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_1 = 308,
			STILETTO_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_1 = 88,
			STILETTO_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_1 = 394,
			STILETTO_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_1 = 156,
			STILETTO_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_1 = 36,
			STILETTO_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_1 = 310,

			STILETTO_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_1 = 133,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_1 = 216,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_1 = 198,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_1 = 205,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_1 = 258,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_1 = 243,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_1 = 301,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_1 = 279,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_1 = 147,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_1 = 300;

	public static int ALMOND_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_1 = 147,
			ALMOND_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_1 = 108,
			ALMOND_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_1 = 225,
			ALMOND_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_1 = 55,
			ALMOND_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_1 = 308,
			ALMOND_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_1 = 88,
			ALMOND_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_1 = 394,
			ALMOND_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_1 = 156,
			ALMOND_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_1 = 38,
			ALMOND_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_1 = 310,

			ALMOND_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_1 = 133,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_1 = 216,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_1 = 198,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_1 = 205,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_1 = 257,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_1 = 242,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_1 = 301,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_1 = 280,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_1 = 146,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_1 = 300;

	public static int ROUNDED_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_1 = 216,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_1 = 143,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_1 = 332,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_1 = 51,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_1 = 455,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_1 = 107,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_1 = 587,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_1 = 227,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_1 = 47,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_1 = 499,

			ROUNDED_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_1 = 208,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_1 = 320,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_1 = 308,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_1 = 300,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_1 = 395,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_1 = 365,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_1 = 465,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_1 = 433,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_1 = 225,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_1 = 475;

	public static int OVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_1 = 216,
			OVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_1 = 144,
			OVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_1 = 332,
			OVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_1 = 51,
			OVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_1 = 455,
			OVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_1 = 107,
			OVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_1 = 587,
			OVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_1 = 223,
			OVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_1 = 47,
			OVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_1 = 500,

			OVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_1 = 208,
			OVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_1 = 320,
			OVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_1 = 308,
			OVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_1 = 300,
			OVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_1 = 395,
			OVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_1 = 365,
			OVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_1 = 465,
			OVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_1 = 433,
			OVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_1 = 225,
			OVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_1 = 475;

	public static int SQUOVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_1 = 216,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_1 = 149,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_1 = 332,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_1 = 62,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_1 = 455,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_1 = 112,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_1 = 587,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_1 = 226,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_1 = 48,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_1 = 500,

			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_1 = 208,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_1 = 320,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_1 = 308,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_1 = 300,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_1 = 393,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_1 = 365,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_1 = 465,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_1 = 433,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_1 = 227,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_1 = 472;

	public static int SQUARE_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_1 = 216,
			SQUARE_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_1 = 148,
			SQUARE_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_1 = 332,
			SQUARE_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_1 = 65,
			SQUARE_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_1 = 455,
			SQUARE_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_1 = 113,
			SQUARE_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_1 = 587,
			SQUARE_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_1 = 226,
			SQUARE_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_1 = 48,
			SQUARE_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_1 = 500,

			SQUARE_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_1 = 208,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_1 = 320,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_1 = 308,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_1 = 300,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_1 = 395,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_1 = 365,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_1 = 465,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_1 = 433,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_1 = 225,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_1 = 471;

	public static int STILETTO_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_1 = 216,
			STILETTO_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_1 = 142,
			STILETTO_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_1 = 332,
			STILETTO_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_1 = 55,
			STILETTO_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_1 = 455,
			STILETTO_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_1 = 105,
			STILETTO_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_1 = 587,
			STILETTO_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_1 = 228,
			STILETTO_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_1 = 47,
			STILETTO_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_1 = 496,

			STILETTO_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_1 = 208,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_1 = 323,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_1 = 309,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_1 = 301,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_1 = 395,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_1 = 367,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_1 = 465,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_1 = 435,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_1 = 226,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_1 = 475;

	public static int ALMOND_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_1 = 216,
			ALMOND_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_1 = 141,
			ALMOND_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_1 = 332,
			ALMOND_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_1 = 55,
			ALMOND_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_1 = 454,
			ALMOND_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_1 = 105,
			ALMOND_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_1 = 587,
			ALMOND_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_1 = 228,
			ALMOND_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_1 = 48,
			ALMOND_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_1 = 497,

			ALMOND_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_1 = 208,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_1 = 320,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_1 = 308,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_1 = 300,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_1 = 395,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_1 = 365,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_1 = 465,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_1 = 433,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_1 = 225,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_1 = 475;

	public static int ROUNDED_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_2 = 144,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_2 = 97,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_2 = 236,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_2 = 62,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_2 = 335,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_2 = 90,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_2 = 426,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_2 = 187,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_2 = 10,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_2 = 304,

			ROUNDED_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_2 = 121,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_2 = 182,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_2 = 220,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_2 = 155,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_2 = 273,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_2 = 179,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_2 = 304,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_2 = 268,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_2 = 158,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_2 = 278;

	public static int OVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_2 = 144,
			OVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_2 = 97,
			OVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_2 = 236,
			OVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_2 = 62,
			OVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_2 = 335,
			OVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_2 = 90,
			OVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_2 = 426,
			OVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_2 = 187,
			OVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_2 = 10,
			OVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_2 = 304,

			OVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_2 = 121,
			OVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_2 = 182,
			OVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_2 = 220,
			OVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_2 = 155,
			OVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_2 = 273,
			OVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_2 = 179,
			OVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_2 = 304,
			OVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_2 = 268,
			OVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_2 = 158,
			OVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_2 = 279;

	public static int SQUOVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_2 = 144,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_2 = 97,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_2 = 236,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_2 = 62,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_2 = 335,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_2 = 90,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_2 = 426,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_2 = 187,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_2 = 10,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_2 = 304,

			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_2 = 121,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_2 = 184,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_2 = 220,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_2 = 155,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_2 = 272,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_2 = 181,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_2 = 304,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_2 = 270,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_2 = 160,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_2 = 279;

	public static int SQUARE_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_2 = 144,
			SQUARE_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_2 = 97,
			SQUARE_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_2 = 236,
			SQUARE_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_2 = 62,
			SQUARE_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_2 = 335,
			SQUARE_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_2 = 90,
			SQUARE_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_2 = 426,
			SQUARE_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_2 = 187,
			SQUARE_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_2 = 10,
			SQUARE_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_2 = 304,

			SQUARE_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_2 = 121,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_2 = 182,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_2 = 220,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_2 = 155,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_2 = 272,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_2 = 179,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_2 = 304,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_2 = 270,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_2 = 158,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_2 = 278;

	public static int STILETTO_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_2 = 144,
			STILETTO_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_2 = 97,
			STILETTO_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_2 = 236,
			STILETTO_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_2 = 62,
			STILETTO_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_2 = 335,
			STILETTO_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_2 = 90,
			STILETTO_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_2 = 426,
			STILETTO_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_2 = 187,
			STILETTO_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_2 = 10,
			STILETTO_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_2 = 304,

			STILETTO_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_2 = 121,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_2 = 182,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_2 = 220,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_2 = 155,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_2 = 274,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_2 = 179,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_2 = 304,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_2 = 270,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_2 = 160,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_2 = 278;

	public static int ALMOND_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_2 = 144,
			ALMOND_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_2 = 97,
			ALMOND_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_2 = 236,
			ALMOND_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_2 = 62,
			ALMOND_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_2 = 335,
			ALMOND_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_2 = 90,
			ALMOND_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_2 = 426,
			ALMOND_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_2 = 187,
			ALMOND_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_2 = 10,
			ALMOND_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_2 = 304,

			ALMOND_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_2 = 121,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_2 = 182,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_2 = 220,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_2 = 155,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_2 = 274,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_2 = 179,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_2 = 304,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_2 = 270,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_2 = 160,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_2 = 278;

	public static int ROUNDED_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_2 = 213,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_2 = 130,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_2 = 350,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_2 = 68,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_2 = 495,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_2 = 115,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_2 = 633,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_2 = 280,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_2 = 10,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_2 = 488,

			ROUNDED_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_2 = 178,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_2 = 323,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_2 = 326,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_2 = 260,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_2 = 406,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_2 = 306,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_2 = 454,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_2 = 474,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_2 = 240,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_2 = 483;

	public static int OVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_2 = 213,
			OVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_2 = 130,
			OVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_2 = 350,
			OVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_2 = 68,
			OVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_2 = 495,
			OVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_2 = 115,
			OVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_2 = 633,
			OVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_2 = 280,
			OVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_2 = 10,
			OVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_2 = 488,

			OVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_2 = 178,
			OVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_2 = 323,
			OVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_2 = 326,
			OVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_2 = 260,
			OVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_2 = 406,
			OVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_2 = 306,
			OVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_2 = 454,
			OVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_2 = 474,
			OVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_2 = 240,
			OVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_2 = 483;

	public static int SQUOVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_2 = 213,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_2 = 130,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_2 = 350,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_2 = 68,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_2 = 495,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_2 = 115,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_2 = 633,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_2 = 280,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_2 = 10,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_2 = 488,

			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_2 = 178,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_2 = 323,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_2 = 326,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_2 = 260,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_2 = 406,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_2 = 306,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_2 = 454,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_2 = 474,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_2 = 240,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_2 = 483;

	public static int SQUARE_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_2 = 213,
			SQUARE_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_2 = 130,
			SQUARE_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_2 = 350,
			SQUARE_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_2 = 68,
			SQUARE_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_2 = 495,
			SQUARE_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_2 = 115,
			SQUARE_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_2 = 633,
			SQUARE_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_2 = 280,
			SQUARE_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_2 = 10,
			SQUARE_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_2 = 488,

			SQUARE_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_2 = 178,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_2 = 323,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_2 = 326,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_2 = 260,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_2 = 406,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_2 = 306,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_2 = 454,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_2 = 474,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_2 = 240,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_2 = 483;

	public static int STILETTO_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_2 = 213,
			STILETTO_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_2 = 130,
			STILETTO_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_2 = 350,
			STILETTO_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_2 = 68,
			STILETTO_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_2 = 495,
			STILETTO_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_2 = 115,
			STILETTO_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_2 = 633,
			STILETTO_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_2 = 280,
			STILETTO_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_2 = 10,
			STILETTO_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_2 = 488,

			STILETTO_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_2 = 178,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_2 = 323,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_2 = 326,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_2 = 260,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_2 = 406,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_2 = 306,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_2 = 454,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_2 = 474,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_2 = 240,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_2 = 483;

	public static int ALMOND_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_2 = 213,
			ALMOND_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_2 = 130,
			ALMOND_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_2 = 350,
			ALMOND_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_2 = 68,
			ALMOND_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_2 = 495,
			ALMOND_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_2 = 115,
			ALMOND_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_2 = 633,
			ALMOND_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_2 = 280,
			ALMOND_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_2 = 10,
			ALMOND_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_2 = 488,

			ALMOND_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_2 = 178,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_2 = 323,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_2 = 326,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_2 = 260,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_2 = 406,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_2 = 306,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_2 = 454,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_2 = 474,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_2 = 240,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_2 = 483;

	public static int ROUNDED_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_3 = 136,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_3 = 97,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_3 = 226,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_3 = 56,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_3 = 315,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_3 = 96,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_3 = 398,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_3 = 190,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_3 = 41,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_3 = 300,

			ROUNDED_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_3 = 115,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_3 = 206,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_3 = 208,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_3 = 182,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_3 = 261,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_3 = 247,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_3 = 307,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_3 = 322,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_3 = 156,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_3 = 321;

	public static int OVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_3 = 136,
			OVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_3 = 97,
			OVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_3 = 226,
			OVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_3 = 56,
			OVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_3 = 315,
			OVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_3 = 96,
			OVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_3 = 398,
			OVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_3 = 190,
			OVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_3 = 42,
			OVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_3 = 300,

			OVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_3 = 115,
			OVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_3 = 206,
			OVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_3 = 208,
			OVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_3 = 182,
			OVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_3 = 261,
			OVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_3 = 247,
			OVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_3 = 307,
			OVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_3 = 322,
			OVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_3 = 157,
			OVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_3 = 322;

	public static int SQUOVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_3 = 136,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_3 = 97,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_3 = 226,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_3 = 56,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_3 = 315,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_3 = 96,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_3 = 398,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_3 = 190,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_3 = 41,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_3 = 300,

			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_3 = 115,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_3 = 206,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_3 = 206,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_3 = 188,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_3 = 260,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_3 = 245,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_3 = 307,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_3 = 322,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_3 = 156,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_3 = 320;

	public static int SQUARE_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_3 = 136,
			SQUARE_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_3 = 97,
			SQUARE_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_3 = 226,
			SQUARE_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_3 = 56,
			SQUARE_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_3 = 315,
			SQUARE_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_3 = 96,
			SQUARE_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_3 = 398,
			SQUARE_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_3 = 190,
			SQUARE_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_3 = 41,
			SQUARE_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_3 = 300,

			SQUARE_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_3 = 115,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_3 = 206,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_3 = 208,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_3 = 182,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_3 = 260,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_3 = 245,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_3 = 307,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_3 = 322,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_3 = 156,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_3 = 319;

	public static int STILETTO_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_3 = 136,
			STILETTO_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_3 = 97,
			STILETTO_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_3 = 226,
			STILETTO_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_3 = 56,
			STILETTO_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_3 = 315,
			STILETTO_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_3 = 96,
			STILETTO_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_3 = 398,
			STILETTO_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_3 = 190,
			STILETTO_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_3 = 42,
			STILETTO_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_3 = 300,

			STILETTO_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_3 = 114,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_3 = 206,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_3 = 209,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_3 = 182,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_3 = 261,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_3 = 247,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_3 = 306,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_3 = 322,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_3 = 158,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_3 = 326;

	public static int ALMOND_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_3 = 136,
			ALMOND_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_3 = 97,
			ALMOND_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_3 = 226,
			ALMOND_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_3 = 56,
			ALMOND_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_3 = 315,
			ALMOND_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_3 = 96,
			ALMOND_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_3 = 398,
			ALMOND_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_3 = 190,
			ALMOND_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_3 = 42,
			ALMOND_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_3 = 300,

			ALMOND_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_3 = 115,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_3 = 210,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_3 = 208,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_3 = 182,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_3 = 261,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_3 = 247,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_3 = 307,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_3 = 322,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_3 = 157,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_3 = 327;

	public static int ROUNDED_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_3 = 202,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_3 = 133,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_3 = 336,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_3 = 60,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_3 = 468,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_3 = 130,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_3 = 593,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_3 = 295,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_3 = 58,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_3 = 486,

			ROUNDED_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_3 = 162,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_3 = 340,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_3 = 305,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_3 = 295,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_3 = 382,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_3 = 404,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_3 = 453,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_3 = 538,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_3 = 230,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_3 = 540;

	public static int OVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_3 = 202,
			OVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_3 = 133,
			OVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_3 = 336,
			OVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_3 = 60,
			OVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_3 = 468,
			OVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_3 = 130,
			OVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_3 = 593,
			OVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_3 = 295,
			OVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_3 = 58,
			OVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_3 = 486,

			OVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_3 = 161,
			OVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_3 = 340,
			OVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_3 = 306,
			OVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_3 = 295,
			OVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_3 = 384,
			OVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_3 = 403,
			OVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_3 = 452,
			OVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_3 = 537,
			OVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_3 = 230,
			OVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_3 = 542;

	public static int SQUOVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_3 = 202,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_3 = 133,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_3 = 336,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_3 = 60,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_3 = 468,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_3 = 130,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_3 = 593,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_3 = 295,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_3 = 58,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_3 = 486,

			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_3 = 162,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_3 = 340,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_3 = 304,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_3 = 295,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_3 = 380,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_3 = 403,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_3 = 452,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_3 = 535,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_3 = 230,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_3 = 538;

	public static int SQUARE_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_3 = 202,
			SQUARE_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_3 = 133,
			SQUARE_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_3 = 336,
			SQUARE_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_3 = 60,
			SQUARE_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_3 = 468,
			SQUARE_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_3 = 130,
			SQUARE_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_3 = 593,
			SQUARE_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_3 = 295,
			SQUARE_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_3 = 58,
			SQUARE_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_3 = 486,

			SQUARE_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_3 = 162,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_3 = 340,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_3 = 304,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_3 = 295,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_3 = 380,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_3 = 403,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_3 = 452,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_3 = 535,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_3 = 230,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_3 = 534;

	public static int STILETTO_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_3 = 202,
			STILETTO_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_3 = 133,
			STILETTO_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_3 = 336,
			STILETTO_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_3 = 60,
			STILETTO_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_3 = 468,
			STILETTO_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_3 = 130,
			STILETTO_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_3 = 593,
			STILETTO_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_3 = 295,
			STILETTO_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_3 = 58,
			STILETTO_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_3 = 486,

			STILETTO_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_3 = 162,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_3 = 340,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_3 = 306,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_3 = 295,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_3 = 384,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_3 = 403,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_3 = 453,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_3 = 538,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_3 = 230,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_3 = 545;

	public static int ALMOND_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_3 = 202,
			ALMOND_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_3 = 133,
			ALMOND_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_3 = 336,
			ALMOND_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_3 = 60,
			ALMOND_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_3 = 468,
			ALMOND_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_3 = 130,
			ALMOND_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_3 = 593,
			ALMOND_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_3 = 295,
			ALMOND_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_3 = 58,
			ALMOND_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_3 = 486,

			ALMOND_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_3 = 162,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_3 = 340,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_3 = 306,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_3 = 295,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_3 = 384,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_3 = 403,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_3 = 453,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_3 = 538,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_3 = 230,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_3 = 545;

	public static int ROUNDED_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_4 = 137,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_4 = 87,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_4 = 240,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_4 = 56,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_4 = 330,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_4 = 102,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_4 = 416,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_4 = 182,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_4 = 25,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_4 = 275,

			ROUNDED_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_4 = 140,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_4 = 182,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_4 = 228,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_4 = 179,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_4 = 282,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_4 = 202,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_4 = 320,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_4 = 278,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_4 = 157,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_4 = 246;

	public static int OVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_4 = 137,
			OVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_4 = 87,
			OVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_4 = 240,
			OVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_4 = 56,
			OVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_4 = 330,
			OVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_4 = 102,
			OVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_4 = 416,
			OVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_4 = 182,
			OVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_4 = 25,
			OVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_4 = 275,

			OVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_4 = 139,
			OVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_4 = 182,
			OVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_4 = 228,
			OVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_4 = 180,
			OVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_4 = 282,
			OVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_4 = 202,
			OVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_4 = 320,
			OVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_4 = 278,
			OVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_4 = 156,
			OVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_4 = 246;

	public static int SQUOVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_4 = 137,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_4 = 87,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_4 = 240,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_4 = 56,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_4 = 330,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_4 = 102,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_4 = 416,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_4 = 182,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_4 = 25,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_4 = 275,

			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_4 = 140,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_4 = 182,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_4 = 228,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_4 = 179,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_4 = 281,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_4 = 202,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_4 = 320,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_4 = 278,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_4 = 156,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_4 = 242;

	public static int SQUARE_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_4 = 137,
			SQUARE_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_4 = 87,
			SQUARE_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_4 = 240,
			SQUARE_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_4 = 56,
			SQUARE_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_4 = 330,
			SQUARE_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_4 = 102,
			SQUARE_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_4 = 416,
			SQUARE_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_4 = 182,
			SQUARE_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_4 = 25,
			SQUARE_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_4 = 275,

			SQUARE_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_4 = 140,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_4 = 182,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_4 = 228,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_4 = 179,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_4 = 281,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_4 = 202,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_4 = 320,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_4 = 278,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_4 = 156,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_4 = 242;

	public static int STILETTO_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_4 = 137,
			STILETTO_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_4 = 85,
			STILETTO_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_4 = 241,
			STILETTO_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_4 = 54,
			STILETTO_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_4 = 330,
			STILETTO_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_4 = 102,
			STILETTO_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_4 = 415,
			STILETTO_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_4 = 180,
			STILETTO_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_4 = 24,
			STILETTO_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_4 = 275,

			STILETTO_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_4 = 139,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_4 = 190,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_4 = 228,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_4 = 190,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_4 = 280,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_4 = 208,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_4 = 320,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_4 = 279,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_4 = 155,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_4 = 255;

	public static int ALMOND_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_4 = 137,
			ALMOND_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_4 = 86,
			ALMOND_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_4 = 241,
			ALMOND_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_4 = 54,
			ALMOND_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_4 = 330,
			ALMOND_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_4 = 103,
			ALMOND_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_4 = 415,
			ALMOND_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_4 = 180,
			ALMOND_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_4 = 24,
			ALMOND_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_4 = 275,

			ALMOND_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_4 = 139,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_4 = 187,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_4 = 229,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_4 = 185,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_4 = 280,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_4 = 208,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_4 = 320,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_4 = 279,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_4 = 157,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_4 = 251;

	public static int ROUNDED_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_4 = 202,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_4 = 120,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_4 = 355,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_4 = 60,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_4 = 490,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_4 = 140,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_4 = 617,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_4 = 277,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_4 = 35,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_4 = 449,

			ROUNDED_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_4 = 198,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_4 = 295,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_4 = 330,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_4 = 292,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_4 = 410,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_4 = 330,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_4 = 470,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_4 = 460,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_4 = 220,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_4 = 405;

	public static int OVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_4 = 203,
			OVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_4 = 120,
			OVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_4 = 355,
			OVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_4 = 60,
			OVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_4 = 490,
			OVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_4 = 140,
			OVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_4 = 617,
			OVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_4 = 277,
			OVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_4 = 35,
			OVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_4 = 449,

			OVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_4 = 198,
			OVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_4 = 295,
			OVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_4 = 330,
			OVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_4 = 292,
			OVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_4 = 412,
			OVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_4 = 330,
			OVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_4 = 468,
			OVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_4 = 460,
			OVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_4 = 220,
			OVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_4 = 408;

	public static int SQUOVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_4 = 201,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_4 = 120,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_4 = 355,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_4 = 60,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_4 = 490,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_4 = 140,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_4 = 617,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_4 = 277,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_4 = 35,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_4 = 448,

			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_4 = 200,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_4 = 295,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_4 = 330,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_4 = 292,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_4 = 410,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_4 = 330,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_4 = 470,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_4 = 460,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_4 = 220,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_4 = 400;

	public static int SQUARE_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_4 = 202,
			SQUARE_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_4 = 120,
			SQUARE_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_4 = 355,
			SQUARE_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_4 = 60,
			SQUARE_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_4 = 490,
			SQUARE_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_4 = 140,
			SQUARE_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_4 = 617,
			SQUARE_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_4 = 277,
			SQUARE_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_4 = 32,
			SQUARE_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_4 = 449,

			SQUARE_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_4 = 200,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_4 = 295,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_4 = 330,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_4 = 292,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_4 = 410,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_4 = 330,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_4 = 470,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_4 = 460,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_4 = 220,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_4 = 400;

	public static int STILETTO_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_4 = 202,
			STILETTO_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_4 = 120,
			STILETTO_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_4 = 355,
			STILETTO_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_4 = 60,
			STILETTO_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_4 = 490,
			STILETTO_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_4 = 140,
			STILETTO_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_4 = 617,
			STILETTO_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_4 = 277,
			STILETTO_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_4 = 33,
			STILETTO_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_4 = 447,

			STILETTO_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_4 = 200,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_4 = 295,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_4 = 330,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_4 = 292,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_4 = 410,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_4 = 330,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_4 = 470,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_4 = 460,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_4 = 220,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_4 = 410;

	public static int ALMOND_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_4 = 202,
			ALMOND_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_4 = 120,
			ALMOND_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_4 = 355,
			ALMOND_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_4 = 60,
			ALMOND_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_4 = 490,
			ALMOND_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_4 = 140,
			ALMOND_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_4 = 617,
			ALMOND_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_4 = 277,
			ALMOND_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_4 = 35,
			ALMOND_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_4 = 448,

			ALMOND_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_4 = 200,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_4 = 295,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_4 = 330,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_4 = 292,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_4 = 410,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_4 = 330,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_4 = 470,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_4 = 460,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_4 = 220,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_4 = 410;

	public static int ROUNDED_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_5 = 140,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_5 = 97,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_5 = 231,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_5 = 56,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_5 = 315,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_5 = 98,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_5 = 411,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_5 = 183,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_5 = 24,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_5 = 282,

			ROUNDED_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_5 = 158,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_5 = 173,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_5 = 224,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_5 = 158,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_5 = 273,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_5 = 211,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_5 = 298,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_5 = 285,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_5 = 154,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_5 = 270;

	public static int OVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_5 = 140,
			OVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_5 = 97,
			OVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_5 = 231,
			OVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_5 = 56,
			OVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_5 = 315,
			OVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_5 = 98,
			OVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_5 = 411,
			OVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_5 = 183,
			OVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_5 = 23,
			OVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_5 = 282,

			OVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_5 = 157,
			OVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_5 = 175,
			OVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_5 = 224,
			OVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_5 = 158,
			OVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_5 = 272,
			OVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_5 = 213,
			OVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_5 = 298,
			OVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_5 = 285,
			OVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_5 = 156,
			OVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_5 = 271;

	public static int SQUOVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_5 = 140,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_5 = 97,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_5 = 231,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_5 = 56,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_5 = 315,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_5 = 98,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_5 = 411,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_5 = 183,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_5 = 23,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_5 = 282,

			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_5 = 158,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_5 = 175,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_5 = 222,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_5 = 160,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_5 = 272,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_5 = 211,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_5 = 300,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_5 = 285,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_5 = 154,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_5 = 270;

	public static int SQUARE_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_5 = 140,
			SQUARE_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_5 = 97,
			SQUARE_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_5 = 231,
			SQUARE_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_5 = 56,
			SQUARE_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_5 = 315,
			SQUARE_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_5 = 98,
			SQUARE_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_5 = 411,
			SQUARE_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_5 = 183,
			SQUARE_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_5 = 23,
			SQUARE_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_5 = 282,

			SQUARE_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_5 = 158,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_5 = 175,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_5 = 220,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_5 = 158,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_5 = 269,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_5 = 210,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_5 = 298,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_5 = 285,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_5 = 155,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_5 = 268;

	public static int STILETTO_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_5 = 140,
			STILETTO_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_5 = 97,
			STILETTO_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_5 = 231,
			STILETTO_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_5 = 56,
			STILETTO_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_5 = 315,
			STILETTO_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_5 = 98,
			STILETTO_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_5 = 411,
			STILETTO_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_5 = 183,
			STILETTO_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_5 = 23,
			STILETTO_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_5 = 282,

			STILETTO_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_5 = 157,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_5 = 182,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_5 = 226,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_5 = 160,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_5 = 274,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_5 = 215,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_5 = 298,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_5 = 284,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_5 = 160,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_5 = 272;

	public static int ALMOND_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_5 = 140,
			ALMOND_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_5 = 97,
			ALMOND_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_5 = 231,
			ALMOND_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_5 = 56,
			ALMOND_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_LEFT_MARGIN_5 = 315,
			ALMOND_TYPE_RIGHT_OPEN_HAND_RING_FINGER_HDPI_TOP_MARGIN_5 = 98,
			ALMOND_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_5 = 411,
			ALMOND_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_5 = 183,
			ALMOND_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_5 = 24,
			ALMOND_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_5 = 282,

			ALMOND_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_LEFT_MARGIN_5 = 156,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_HDPI_TOP_MARGIN_5 = 176,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_LEFT_MARGIN_5 = 225,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_HDPI_TOP_MARGIN_5 = 160,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_LEFT_MARGIN_5 = 274,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_HDPI_TOP_MARGIN_5 = 214,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_LEFT_MARGIN_5 = 298,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_HDPI_TOP_MARGIN_5 = 285,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_LEFT_MARGIN_5 = 158,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_HDPI_TOP_MARGIN_5 = 274;

	public static int ROUNDED_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_5 = 208,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_5 = 118,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_5 = 343,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_5 = 45,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_5 = 470,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_5 = 127,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_5 = 613,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_5 = 262,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_5 = 35,
			ROUNDED_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_5 = 440,

			ROUNDED_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_5 = 228,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_5 = 320,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_5 = 328,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_5 = 290,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_5 = 403,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_5 = 385,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_5 = 450,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_5 = 505,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_5 = 225,
			ROUNDED_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_5 = 485;

	public static int OVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_5 = 209,
			OVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_5 = 118,
			OVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_5 = 343,
			OVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_5 = 45,
			OVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_5 = 470,
			OVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_5 = 127,
			OVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_5 = 613,
			OVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_5 = 262,
			OVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_5 = 33,
			OVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_5 = 440,

			OVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_5 = 228,
			OVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_5 = 320,
			OVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_5 = 328,
			OVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_5 = 290,
			OVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_5 = 403,
			OVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_5 = 385,
			OVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_5 = 450,
			OVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_5 = 505,
			OVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_5 = 225,
			OVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_5 = 485;

	public static int SQUOVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_5 = 208,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_5 = 118,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_5 = 343,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_5 = 45,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_5 = 472,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_5 = 127,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_5 = 613,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_5 = 262,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_5 = 33,
			SQUOVAL_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_5 = 440,

			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_5 = 228,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_5 = 320,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_5 = 326,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_5 = 290,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_5 = 400,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_5 = 385,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_5 = 448,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_5 = 505,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_5 = 225,
			SQUOVAL_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_5 = 483;

	public static int SQUARE_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_5 = 208,
			SQUARE_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_5 = 118,
			SQUARE_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_5 = 343,
			SQUARE_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_5 = 45,
			SQUARE_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_5 = 470,
			SQUARE_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_5 = 127,
			SQUARE_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_5 = 613,
			SQUARE_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_5 = 262,
			SQUARE_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_5 = 33,
			SQUARE_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_5 = 440,

			SQUARE_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_5 = 228,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_5 = 320,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_5 = 325,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_5 = 290,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_5 = 398,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_5 = 385,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_5 = 447,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_5 = 505,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_5 = 225,
			SQUARE_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_5 = 483;

	public static int STILETTO_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_5 = 208,
			STILETTO_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_5 = 118,
			STILETTO_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_5 = 343,
			STILETTO_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_5 = 45,
			STILETTO_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_5 = 470,
			STILETTO_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_5 = 127,
			STILETTO_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_5 = 613,
			STILETTO_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_5 = 262,
			STILETTO_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_5 = 32,
			STILETTO_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_5 = 440,

			STILETTO_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_5 = 228,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_5 = 320,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_5 = 330,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_5 = 290,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_5 = 405,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_5 = 385,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_5 = 450,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_5 = 505,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_5 = 228,
			STILETTO_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_5 = 485;

	public static int ALMOND_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_5 = 208,
			ALMOND_TYPE_RIGHT_OPEN_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_5 = 118,
			ALMOND_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_5 = 343,
			ALMOND_TYPE_RIGHT_OPEN_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_5 = 45,
			ALMOND_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_5 = 470,
			ALMOND_TYPE_RIGHT_OPEN_HAND_RING_FINGER_XHDPI_TOP_MARGIN_5 = 127,
			ALMOND_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_5 = 613,
			ALMOND_TYPE_RIGHT_OPEN_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_5 = 262,
			ALMOND_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_5 = 35,
			ALMOND_TYPE_RIGHT_OPEN_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_5 = 440,

			ALMOND_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_LEFT_MARGIN_5 = 228,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_INDEX_FINGER_XHDPI_TOP_MARGIN_5 = 320,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_LEFT_MARGIN_5 = 328,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_MIDDLE_FINGER_XHDPI_TOP_MARGIN_5 = 290,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_LEFT_MARGIN_5 = 403,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_RING_FINGER_XHDPI_TOP_MARGIN_5 = 385,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_LEFT_MARGIN_5 = 450,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_PINKIE_FINGER_XHDPI_TOP_MARGIN_5 = 505,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_LEFT_MARGIN_5 = 228,
			ALMOND_TYPE_RIGHT_CLOSED_HAND_THUMB_FINGER_XHDPI_TOP_MARGIN_5 = 485;

	public static Object index_nail_color_object, middle_nail_color_object,
			ring_nail_color_object, pinkie_nail_color_object,
			thumb_nail_color_object, brush_color,
			current_index_nail_color_object, current_middle_nail_color_object,
			current_ring_nail_color_object, current_pinkie_nail_color_object,
			current_thumb_nail_color_object;

	public static int selected_base_index = 0, selected_hand_color_type = 1;
	public static List<Object> color_picked_list;
	public static List<Object> color_picked_list_inDraw;

	// public static List<String>used_color_list;

	public static class Config {
		public static final boolean DEVELOPER_MODE = false;
	}

	// public static void
	// copyColorToInDrawList(List<Object>srcList,List<Object>destinationList){
	// if(color_picked_list_inDraw==null)
	// color_picked_list_inDraw=new ArrayList<Object>();
	// color_picked_list_inDraw=destinationList;
	// //copy logic
	// Collections.copy(color_picked_list_inDraw, srcList);
	// }
	public static void addColorToCPListaa(Object colorCode) {
		if (color_picked_list == null)
			color_picked_list = new ArrayList<Object>();
		if (color_picked_list.size() < 4)
			color_picked_list.add(colorCode);
	}

	public static void removeColorFromCPList(int position) {
		System.out.println("Position to delete " + position);
		if (color_picked_list != null && position < color_picked_list.size())
			color_picked_list.remove(position);
	}

	public static List<Object> getListOfColor() {
		return color_picked_list;
	}

	public static void removeAllColorFromCPList() {
		color_picked_list = new ArrayList<Object>();
	}

	public static void setListOfColorsToCPList(List<Object> color_list) {
		// if (color_picked_list != null)
		// color_picked_list = null;
		color_picked_list = color_list;
	}

	public static void setListOfColorsInDraw(List<Object> color_list) {
		if (color_picked_list_inDraw == null)
			color_picked_list_inDraw = new ArrayList<Object>();
		color_picked_list_inDraw = color_list;
	}

	public static List<Object> getListOfColorInDraw() {
		return color_picked_list_inDraw;
	}

	public static void removeListOfColorInDraw(int position) {
		System.out.println("Position to delete " + position);
		if (color_picked_list_inDraw != null
				&& position < color_picked_list_inDraw.size())
			color_picked_list_inDraw.remove(position);
	}

	public Object getIndex_nail_color_object() {
		return index_nail_color_object;
	}

	/**
	 * Call this method to set Color or Bitmap to all nail's object
	 * 
	 * @param color_object
	 *            - color or bitmap
	 */
	public static void setColorToAllNails(Object color_object) {
		Constants.index_nail_color_object = Constants.middle_nail_color_object = Constants.pinkie_nail_color_object = Constants.ring_nail_color_object = Constants.thumb_nail_color_object = color_object;
		System.out.println("Constants.index_nail_color_object "
				+ Constants.index_nail_color_object + " " + color_object);
	}

	/**
	 * Call this method to check whether nails object are empty or contains some
	 * value
	 * 
	 * @return true or false
	 */
	public static boolean isNailsObjectEmpty() {
		boolean status = true;
		if (Constants.index_nail_color_object != null)
			status = false;
		else if (Constants.middle_nail_color_object != null)
			status = false;
		else if (Constants.ring_nail_color_object != null)
			status = false;
		else if (Constants.pinkie_nail_color_object != null)
			status = false;
		else if (Constants.thumb_nail_color_object != null)
			status = false;
		return status;
	}

	/**
	 * Call this method to get nails object, which stored color or bitmap.
	 * 
	 * @param position
	 *            - position of nail thumb = 0, index = 1, middle = 2, ring =3,
	 *            pinkie = 4;
	 * @return object of nail it can be integer(For color) or bitmap(For pattern
	 *         or for stored design)
	 */
	public static Object getNailsObject(int position) {
		Object temp_Object = null;
		if (position == Constants.THUMB_FINGER) {
			temp_Object = Constants.thumb_nail_color_object;
		} else if (position == Constants.INDEX_FINGER) {
			temp_Object = Constants.index_nail_color_object;
		} else if (position == Constants.MIDDLE_FINGER) {
			temp_Object = Constants.middle_nail_color_object;
		} else if (position == Constants.RING_FINGER) {
			temp_Object = Constants.ring_nail_color_object;
		} else if (position == Constants.PINKIE_FINGER) {
			temp_Object = Constants.pinkie_nail_color_object;
		}

		System.out.println("TEMP OBJECT ++++++" + temp_Object);
		return temp_Object;
	}

	/**
	 * Call this method to left and top margin to nails after manually changing
	 * nail position on screen
	 * 
	 * @param position
	 *            - nail number
	 * @param leftMargin
	 *            - integer
	 * @param topMargin
	 *            - integer
	 */
	public static void setCurrentNailMargin(int position, int leftMargin,
			int topMargin) {
		if (position == Constants.THUMB_FINGER) {
			Constants.CURRENT_HAND_THUMB_FINGER_LEFT_MARGIN = leftMargin;
			Constants.CURRENT_HAND_THUMB_FINGER_TOP_MARGIN = topMargin;
		} else if (position == Constants.INDEX_FINGER) {
			Constants.CURRENT_HAND_INDEX_FINGER_LEFT_MARGIN = leftMargin;
			Constants.CURRENT_HAND_INDEX_FINGER_TOP_MARGIN = topMargin;
		} else if (position == Constants.MIDDLE_FINGER) {
			Constants.CURRENT_HAND_MIDDLE_FINGER_LEFT_MARGIN = leftMargin;
			Constants.CURRENT_HAND_MIDDLE_FINGER_TOP_MARGIN = topMargin;
		} else if (position == Constants.RING_FINGER) {
			Constants.CURRENT_HAND_RING_FINGER_LEFT_MARGIN = leftMargin;
			Constants.CURRENT_HAND_RING_FINGER_TOP_MARGIN = topMargin;
		} else if (position == Constants.PINKIE_FINGER) {
			Constants.CURRENT_HAND_PINKIE_FINGER_LEFT_MARGIN = leftMargin;
			Constants.CURRENT_HAND_PINKIE_FINGER_TOP_MARGIN = topMargin;
		}
	}

	/**
	 * Call this method to save bitmap to file system with name Image-(Current
	 * time in millis).jpg
	 * 
	 * @param context
	 * @param finalBitmapOfHand
	 *            - bitmap to save
	 */

	/**
	 * Call this method to close globally stored activity
	 */
	public static void removeActivityFromStack() {
		if (ACTIVITY_TO_CLOSE != null)
			ACTIVITY_TO_CLOSE.finish();
	}
}
